# Generated by Django 2.2.7 on 2019-11-07 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('matricula', models.CharField(editable=False, max_length=8, verbose_name='Matricula')),
                ('cidade', models.CharField(max_length=40, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=20, verbose_name='Estado')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=8, verbose_name='Codigo')),
                ('faculdade', models.CharField(max_length=150, verbose_name='Instituição de ensino')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horaria')),
                ('coordenador', models.CharField(max_length=100, verbose_name='Coordernador')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='data')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
        ),
    ]
