# Generated by Django 2.2.7 on 2019-11-06 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191105_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
