# Generated by Django 2.2.7 on 2019-11-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191105_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(editable=False, max_length=8, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='codigo',
            field=models.CharField(editable=False, max_length=8, verbose_name='Codigo'),
        ),
    ]
