# Generated by Django 2.2.7 on 2019-11-06 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191105_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aluno'),
        ),
    ]
